name: Sinbad Production Workflow
on:
  push:
    tags:
    - production_*
jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Pages Production
    environment: Production
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.extract_version.outputs.RELEASE_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: NPM Install
      uses: "./.github/actions/npm_install"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: production
    - name: Versioning
      uses: "./.github/actions/tag"
      with:
        release_type: production
    - name: Extract version
      id: extract_version
      run: echo "RELEASE_VERSION=${version}" >> $GITHUB_OUTPUT
    - name: Publish to Cloudflare Pages Production
      uses: "./.github/actions/publish_to_pages_production"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  send_slack_notification:
      name: Send Slack notification
      runs-on: ubuntu-latest
      environment: Production
      if: always()
      needs: [build_test_and_publish]
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Send Slack Notification
        uses: "./.github/actions/send_slack_notifications"
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          release_type: Production
          version: ${{ needs.build_test_and_publish.outputs.RELEASE_VERSION}}
