name: Sinbad Staging Workflow
on:
  push:
    branches:
    - master

jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Staging
    runs-on: Runner_16cores_Deriv-app
    environment: Staging
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tag
      uses: "./.github/actions/tag"
    - name: Npm Install
      uses: "./.github/actions/npm_install"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: staging
    - name: Versioning
      uses: "./.github/actions/tag"
      with:
        release_type: staging
    - name: Extract version
      id: extract_version
      run: echo "RELEASE_VERSION=${version}" >> $GITHUB_OUTPUT
    - name: Publish to Cloudflare Pages Staging
      uses: "./.github/actions/publish_to_pages_staging"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  send_slack_notification:
    name: Send Slack notification
    runs-on: Runner_16cores_Deriv-app
    environment: Staging
    if: always()
    needs: [build_test_and_publish]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Send Slack Notification
      uses: "./.github/actions/send_slack_notifications"
      with:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: ${{ env.WORKFLOW_CONCLUSION }}
        release_type: Staging
        version: ${{ needs.build_test_and_publish.outputs.RELEASE_VERSION}}