name: Sinbad Test Workflow
on:
  pull_request:
    branches:
    - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu_latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install npm packages
      uses: "./.github/actions/npm_install_from_cache"
    - name: Build
      uses: "./.github/actions/build"
